#!/usr/bin/env bats
load helper

setup() {
  H="$BATS_TEST_TMPDIR/home"; SK="$BATS_TEST_TMPDIR/skills"
  setup_repo
  cfg_set '.harnesses = ["claude","codex"]'
}
engine() { "$ROOT/bin/install-codex.sh" --home "$H" --skills "$SK"; }
agents() { "$ROOT/bin/install-codex.sh" --home "$H" --repo "$REPO"; }
toml() { python3 -c 'import tomllib,sys,json; print(json.dumps(tomllib.load(open(sys.argv[1],"rb"))))' "$1"; }

@test "every role and skill has readable frontmatter with a description" {
  for f in "$ROOT"/roles/*.md "$ROOT"/skills/*/SKILL.md; do
    d="$(yq --front-matter=extract -r '.description // ""' "$f")"
    [ -n "$d" ] || { echo "no description in $f"; false; }
  done
}

@test "installs the engine and one skill per Compasso skill, renamed for Codex" {
  run engine
  [ "$status" -eq 0 ]
  [ -f "$H/engine/bin/config.sh" ] && [ -f "$H/engine/roles/security.md" ] && [ -f "$H/engine/.compasso-engine" ]
  for s in "$ROOT"/skills/*/; do
    n="$(basename "$s")"
    [ "$(yq --front-matter=extract -r .name "$SK/compasso-$n/SKILL.md")" = "compasso-$n" ]
  done
}

@test "skills point at the engine and at Codex commands, never at the Claude plugin" {
  engine >/dev/null
  [ "$(cat "$SK"/*/SKILL.md | grep -c 'CLAUDE_PLUGIN_ROOT')" -eq 0 ]
  [ "$(cat "$SK"/*/SKILL.md | grep -c '/compasso:')" -eq 0 ]
  grep -q "bash $H/engine/bin/tracker.sh check" "$SK/compasso-story/SKILL.md"
  grep -q '\$compasso-plan' "$SK/compasso-feature/SKILL.md"
  grep -q 'custom agent `compasso-<role>`' "$SK/compasso-story/SKILL.md"
}

@test "re-installing converges and removes skills that no longer exist" {
  engine >/dev/null
  mkdir -p "$SK/compasso-old" && printf -- '---\nname: compasso-old\n---\n<!-- generated by compasso install-codex -->\n' > "$SK/compasso-old/SKILL.md"
  run engine
  [ "$status" -eq 0 ]
  [ ! -e "$SK/compasso-old" ]
}

@test "a skill or engine that is not Compasso's is never overwritten" {
  mkdir -p "$SK/compasso-plan" && echo "mine" > "$SK/compasso-plan/SKILL.md"
  run engine
  [ "$status" -eq 1 ]
  [[ "$output" == *"is not Compasso's"* ]] || false
  [ "$(cat "$SK/compasso-plan/SKILL.md")" = mine ]
  [ ! -e "$H/engine" ]
  rm -rf "$SK"; mkdir -p "$H/engine" && echo x > "$H/engine/keep"
  run engine
  [ "$status" -eq 1 ]
  [ -f "$H/engine/keep" ]
}

@test "an engine path with shell syntax is refused" {
  run "$ROOT/bin/install-codex.sh" --home "$BATS_TEST_TMPDIR/my home" --skills "$SK"
  [ "$status" -eq 1 ]
  [[ "$output" == *"refusing"* ]] || false
}

@test "per project: one valid Codex agent per role with the configured model and effort" {
  engine >/dev/null
  cfg_set '.models.codex.builder = {"model": "gpt-6-luna", "effort": "low"}'
  run agents
  [ "$status" -eq 0 ]
  for r in "$ROOT"/roles/*.md; do
    n="$(basename "$r" .md)"
    j="$(toml "$REPO/.codex/agents/compasso-$n.toml")"
    [ "$(jq -r .name <<<"$j")" = "compasso-$n" ]
    [ -n "$(jq -r .description <<<"$j")" ]
    [[ "$(jq -r .developer_instructions <<<"$j")" == *"$H/engine/bin"* ]] || false
  done
  [ "$(toml "$REPO/.codex/agents/compasso-builder.toml" | jq -c '[.model, .model_reasoning_effort]')" = '["gpt-6-luna","low"]' ]
  [ "$(toml "$REPO/.codex/agents/compasso-security.toml" | jq -c '[.model, .model_reasoning_effort]')" = '["gpt-6-astra","high"]' ]
}

@test "per project: refused when codex is not a harness, or before the engine is installed" {
  run agents
  [ "$status" -eq 1 ]
  [[ "$output" == *"run install-codex.sh first"* ]] || false
  engine >/dev/null
  cfg_set '.harnesses = ["claude"]'
  run agents
  [ "$status" -eq 1 ]
  [[ "$output" == *"codex is not in harnesses"* ]] || false
}

@test "per project: an agent file that is not Compasso's is never overwritten" {
  engine >/dev/null
  mkdir -p "$REPO/.codex/agents" && echo 'name = "mine"' > "$REPO/.codex/agents/compasso-tester.toml"
  run agents
  [ "$status" -eq 1 ]
  [ "$(cat "$REPO/.codex/agents/compasso-tester.toml")" = 'name = "mine"' ]
}
